// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function construct(b) {
  if (b) {
    return {
            ...((function (opt) {
                    opt ? ({
                          n: opt
                        }) : ({});
                  }).apply(null, 0))
          };
  } else {
    return {};
  }
}

var er = {};

exports.construct = construct;
exports.er = er;
/* No side effect */
