// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var x = Math.random() < 2.0 ? undefined : 1;

var r = {
  ...((function (opt) {
          opt ? ({
                x: opt
              }) : ({});
        }).apply(null, x))
};

exports.x = x;
exports.r = r;
/* x Not a pure module */
